### ISSUE TITLE
robohash is down ?

### ISSUE THREAD

**Issue by sojan-official** [e1ven/Robohash#12]
the site is not accessible at the moment. everything okay ?

**Comment by TheAznShumai** [comment]
Rubohash seems to be down today.

**Comment by sdkindy** [comment]
Seconded. Any idea when it'll be back up, @e1ven?

**Comment by sdkindy** [comment]
Seconded. Any idea when it'll be back up, @e1ven?

**Comment by dorton** [comment]
yup, still down.  Getting a 502.

**Comment by devill** [comment]
It's down for me as well... It would be nice to know if it will be back up by Saturday

**Comment by SagareGanesh** [comment]
@e1ven can you please see why this site is down. 
thanks

**Comment by devill** [comment]
Since I need this service running by Saturday, and @e1ven is not responding I'm considering to create a mirror. Would any of you be willing to jump into a google hangouts and help me deploy this thing to Heroku?

**Comment by devill** [comment]
It would be nice if I didn't have to do it alone.

**Comment by vinhcp** [comment]
@devill When it's working well again?
Thanks

**Comment by devill** [comment]
I already found help! :)

**Comment by devill** [comment]
@kbence Was nice enough to make robohash deployable to Heroku. If any of you needs a quick replacement please deploy your own Heroku instance.

**Comment by sojan-official** [comment]
went ahead and deployed @kbence repo on heroku.

**Comment by jbcpollak** [comment]
Seems Robohash.org wen't down again, should I file another bug?

**Comment by faridmovsumov** [comment]
site is down again please fix. https://robohash.org/49c9cd05f52ef04074114811a5e2d942?set=set4&gravatar=hashed&size=75x75
