### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by Yamakaky** [e1ven/Robohash#13]
It would be cool

**Comment by e1ven** [comment]
If I were doing it today, I probably would, but I don't have the original artwork in svg format. 
If you'd like to trace it, I'd love to add svgs.

**Comment by Yamakaky** [comment]
Oh, I thought you generated them on the fly.

**Comment by e1ven** [comment]
They're generated on the fly by combining several layers of images - A random face base, a random smile, a random set of eyes, etc. Take a look at https://github.com/e1ven/Robohash/tree/master/robohash/sets/set1
