### ISSUE TITLE
create a set based cat-avatar-generator

### ISSUE THREAD

**Issue by elf-pavlik** [e1ven/Robohash#17]
https://www.peppercarrot.com/en/article391/cat-avatar-generator

> Source code and graphics CC-By [1] David Revoy [2] ( artworks of Cats and open-raster file )

[2016_cat-generator.zip](https://github.com/e1ven/Robohash/files/998857/2016_cat-generator.zip)

**Comment by e1ven** [comment]
I exported out the cats from his ora file, and integrated them in.
It shouldn't ever give you a car unless you ask for it, to keep existing avatar's static.
If you pass set=set4, then it should now offer you one. 

Example:

https://robohash.org/WORDSGOHERE?set=set4

**Comment by elf-pavlik** [comment]
sweet! THANK YOU :smile_cat:

**Comment by crissesoto** [comment]
set 4 for cats is not working, please help

**Comment by ghost** [comment]
There's also https://davidrevoy.com/article720 :bird:
