### ISSUE TITLE
10% chance of slow response

### ISSUE THREAD

**Issue by Engelberg** [e1ven/Robohash#18]
I've got a page that downloads 10-ish robohash robots.  I'm finding that often 1 of the 10 robots will take about a minute to download while the rest are rather quick.  Is this normal?

**Comment by Engelberg** [comment]
Is there some sort of intentional throttling going on to prevent denial-of-service attacks, and if so, what is the limit?  Is there a simple package of the website that I can easily deploy to my own server to avoid this?  Thanks.

**Comment by e1ven** [comment]
You should be able to use the package you're commenting on to run your own website, just run webfront.py

There shouldn't be any deliberate slowdown, but there are several machines behind the LB. 
I've added a monitor script to watch the various machines. It looks like one of them had a FW issue which I resolved, thanks!
