### ISSUE TITLE
Bump the version

### ISSUE THREAD

**Issue by patrickcjh** [e1ven/Robohash#21]
Could you release a new version to PyPI, because v1.0.0 is affected by the sorting issue?

**Comment by eeriksp** [comment]
The latest published version does not support cat avatars.
In order to get this capability, one needs to use

`pip install -U git+https://github.com/e1ven/Robohash.git`

instead of

`pip install robohash`

**Comment by e1ven** [comment]
Good point, thanks. I didn't realize people were really using the version I pushed to pip.
I'll revise it at some point, I just don't have that dev env anymore, so I'd probably need to regenerate keys/etc, and I haven't had a day to dedicate to it :/

**Comment by e1ven** [comment]
I've updated it at Pypi, thanks for the reminder.
