### ISSUE TITLE
Site is down.

### ISSUE THREAD

**Issue by faridmovsumov** [e1ven/Robohash#23]
Please fix. 

Example url: https://robohash.org/49c9cd05f52ef04074114811a5e2d942?set=set4&gravatar=hashed&size=75x75

![image](https://user-images.githubusercontent.com/1541412/35528321-8d2839fc-053e-11e8-9e7c-c2b288502519.png)

**Comment by e1ven** [comment]
Digital Ocean is doing reboots for Spectre migration.
I'll try to keep rebooting instances out of the LB

**Comment by faridmovsumov** [comment]
Thank you very much for information

**Comment by faridmovsumov** [comment]
BTW You have a great service I really like it. Especially cats are really cute

**Comment by e1ven** [comment]
Thanks :)

I've added two more sites in rotation - If it doesn't get faster by EOD, I'll add some more.
