### ISSUE TITLE
Usage Instructions

### ISSUE THREAD

**Issue by markifornia** [e1ven/Robohash#24]
I've managed to import the Robohash module just fine by creating an arbitrary file. 

Does the script run on the fly or does anything need to be compiled or processed first? 

Any assistance much appreciated - great library, I'd like to get better at understanding it's usage and hopefully provide more useful feedback. 

Thanks,
Mark

**Comment by e1ven** [comment]
It needs the pngs in place first. Other than that, you should be good to go. If you have any other specific questions, feel free to re-open.
