### ISSUE TITLE
URL's are not responding

### ISSUE THREAD

**Issue by teug91** [e1ven/Robohash#25]
The API responds with a URL, but the URL is non-responding. I can see robohash.org has the same issue. Pretty sure it worked yesterday.

`Failed to load resource: net::ERR_EMPTY_RESPONSE`

**Comment by KevinKelbie** [comment]
The same thing just started happening for me, is there a way to not rely on an external server?

**Comment by e1ven** [comment]
I've added an additional server, that should help keep up with the load. 
Let me know if you keep seeing issues.

@KevinKelbie  - You can totally run your own server. It's the preferred method if you're going to be making a lot of hits to it. Use the code from the repo you're commenting it. :)

**Comment by teug91** [comment]
Thanks! Issue can be closed as far as I'm concerned.
