### ISSUE TITLE
set5 isn't being displayed and slower than the other sets

### ISSUE THREAD

**Issue by simonfranz** [e1ven/Robohash#31]
Through the caching the new set5 isnt displayed on the main page.

Besides that, there seems to be an performance-issue. 
Generating a hash with set 4 are at average at 1 second. Generating a image for a hash with set5 need up to 10 seconds. Is there a need to resize the images of set5 to decrease response-time?

best regards

**Comment by simonfranz** [comment]
even 2 month later the set5 is not displayed on the front-page. So there might be some other kind of magic (aka setting) why this set is not displayed.

**Comment by Flimm** [comment]
I also experience very slow responses for set5, both locally and from robohash.org .

**Comment by e1ven** [comment]
Set5 is absolutely bigger :/
I'd rather not reduce it if possible, since staying with the largest available images will give the highest quality.

```
2.9M	set1
1.2M	set2
9.4M	set3
8.0M	set4
 28M	set5
```

I've enabled cloudflare for the site, hopefully that should make it faster for you?
