### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by faridmovsumov** [e1ven/Robohash#35]
Could you please renew ssl certificate?

![image](https://user-images.githubusercontent.com/1541412/68018051-733b3780-fc98-11e9-8312-bd14c963067e.png)

**Comment by chenav** [comment]
+1

**Comment by e1ven** [comment]
My bad, thanks. Fixed + moved it to LE.

**Comment by weaverryan** [comment]
Thank you @e1ven - and thanks for code + site ❤️
