### ISSUE TITLE
Version on PyPI is newer than version on GitHub

### ISSUE THREAD

**Issue by Flimm** [e1ven/Robohash#40]
Here is the page on PyPI:

https://pypi.org/project/robohash/

As you can see, the current version on PyPI is 1.1, which was released on 1 March 2020.

However, here in GitHub, the version in setup.py is 1.0, and the latest commit is in August 2019.

**Comment by e1ven** [comment]
There weren't any changes, I just had to bump the version so I could push it.

```
Robohash e1ven$ git diff -U0
diff --git a/setup.py b/setup.py
index 13c4770..6a7ac13 100644
--- a/setup.py
+++ b/setup.py
@@ -12 +12 @@ setup(
-    version='1.0',
+    version='1.1',
@@ -18 +18 @@ setup(
-    download_url='https://github.com/e1ven/Robohash/tarball/1.0',
+    download_url='https://github.com/e1ven/Robohash/tarball/1.1',
Robohash e1ven$ 
```
