### ISSUE TITLE
robohash.org is returning 525, 520, and 500 errors

### ISSUE THREAD

**Issue by nlaveck** [e1ven/Robohash#44]
I can reproduce this by going directly to robohash.org and clicking generate a few times.  Maybe Cloudflare is having issues?

**Comment by e1ven** [comment]
The number of non-cached requests has gone up dramatically since 9am ET. 
I've added some new servers. :(

**Comment by jfloff** [comment]
I don't know if its related but I found out that the size parameter is always returning 500 for me. 

Example:
`https://robohash.org/test.png` ✅  all good
`https://robohash.org/test.png?size=150x150`  🛑  500 Internal Server Error
