### ISSUE TITLE
I created a .net copy based on SkiaSharp

### ISSUE THREAD

**Issue by taurenshaman** [e1ven/Robohash#45]
Excellent work! ♥♥♥♥♥♥♥
I translated to C# 😄
https://github.com/taurenshaman/veins.skiasharp/blob/master/Veins.SkiaSharp/Veins.Art/HashImage/Robohash.cs

**Comment by e1ven** [comment]
Very cool, I hope it was fun :)
A word of warning, Livings/GeometricBird doesn't have a posted license so you may not be allowed to distribute it.

**Comment by taurenshaman** [comment]
Thank you very much!
I added a [License-Robohash](https://github.com/taurenshaman/veins.skiasharp/blob/master/Veins.SkiaSharp/Veins.Art/HashImage/License-Robohash.txt) file.
