### ISSUE TITLE
Is Robohash (not the website, but the image generator) down?

### ISSUE THREAD

**Issue by risafj** [e1ven/Robohash#47]
Hi @e1ven,

I have noticed that all of the requests I've made since at least about 4 hours ago (could have been going on for longer, and I just didn't realise) have returnedd a `522 connection timed out`. Wondering if your server is down?

e.g. https://robohash.org/test123
 
<img width="1164" alt="robohash_org___522__Connection_timed_out" src="https://user-images.githubusercontent.com/43341670/124383044-668ca380-dd05-11eb-9d25-cfcdf848c358.png">

By the way, great project, I absolutely love the different image sets (especially the cats)!

**Comment by e1ven** [comment]
I had restarted the gateway a bit ago, is that better?

**Comment by risafj** [comment]
Yes, robots are loading now! Thank you so much 🎉
