### ISSUE TITLE
robohash.org is down

### ISSUE THREAD

**Issue by Augustin-FL** [e1ven/Robohash#50]
Hi @e1ven,

robohash.org seems down again,

Could you please have a look?

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/9406403/160629876-4380240a-a044-4cb9-b8f5-8e5b8004015e.png">

**Comment by greplerio** [comment]
new hashes aren’t being generated, but old ones seem to be cached.

**Comment by n8-dev** [comment]
Seems to be working now.
`https://robohash.org/test1234`
![https://robohash.org/test1234](https://robohash.org/test1234)
