### ISSUE TITLE
500 Error when submitting a request

### ISSUE THREAD

**Issue by jonjojr** [e1ven/Robohash#51]
I submit a testing request: https://robohash.org/max@redbull.com?set=set5&bgset=bg2 and get a 500 error, but if I submit https://robohash.org/max@redbullcom?set=set5&bgset=bg2 (without the dot in the email) it works fine
others work fine: https://robohash.org/sergio@redbull.com?set=set5&bgset=bg2
Just wanted you to be aware that's all. :-)

**Comment by e1ven** [comment]
Thanks, I'm seeing all three load for me here :(
Are they loading for you now? I wonder if it was transient?

**Comment by e1ven** [comment]
Ah, I am able to replicate it on some requests - I'll look into it, thanks

**Comment by e1ven** [comment]
@jonjojr  - I think I may have it fixed. Can you try and let me know if it works for you?
Thanks again!

**Comment by jonjojr** [comment]
yep, it looks like its fixed now. all three loading. awesome, thanks.

**Comment by e1ven** [comment]
🥳
