### ISSUE TITLE
500 errors continue

### ISSUE THREAD

**Issue by aimichal** [e1ven/Robohash#52]
Similarly to https://github.com/e1ven/Robohash/issues/51, more 500s:

```
$ curl https://robohash.org/asdf\?size\=32x32
<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>
```

**Comment by e1ven** [comment]
Let me see what I can do- It looks unrelated to #51, but I'll try to patch around it

**Comment by e1ven** [comment]
Thanks for the note - I've pushed out a change that I hope should resolve it for you.

As a side note, going back and looking at this code years later - I really could have written this better :)
